name: Build Back-end

on:
  push:
    paths-ignore:
      - "packages/web/**" # don't run if only web has changed

  jobs:
    build:
      name: Build Back-end
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x, 18.x]
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Setup node ${{ matrix.node-version }}
          uses: actions/setup-node@master
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: yarn

        - name: Run tests
          working-directory: packages/server
          run: yarn test